server:
  AppVersion: 0.1
  Port: 8080
  PprofPort: 5558
  ReadTimeout: 3
  WriteTimeout: 3
  CtxDefaultTimeout: 3
  ExternalTimeout : 3
  Debug: true
  UseTls: false
  CertFile: "./ssl/server.crt"
  KeyFile: "./ssl/server.key"

logger:
  Development: true
  DisableCaller: false
  Encoding: json
  Level: info
  EnableFile: false
  InfoFileName: "./logs/server.log"
  MaxBackups: 5
  MaxAge: 30
  MaxSize: 1

alchemy:
  token: key

etherscan:
  token: key


